services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ra-backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ra-frontend
    ports:
      - "80:80"
    # depends_on:
    #   - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

