services:
  backend-was:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ra-was
    ports:
      - "8000:8000"
    networks:
      - backend

  backend-ws:
    image: nginx:latest
    container_name: ra-ws
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-was
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

networks:
  backend:
    driver: bridge
