# name: Build & Bump Infra
# on:
#   push:
#     branches: [ main, dev ]
#   workflow_dispatch:

# permissions:
#   contents: read
#   packages: write

# jobs:
#   build-and-pr:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE: ghcr.io/${{ github.repository_owner }}/seexr-api-ra   # 서비스별로 수정
#       TAG_SHA: sha-${{ github.sha }}
#       INFRA_REPO: pikaybh/seexr-infra                              # 본인 것으로 수정
#       OVERLAY_PATH: ${{ github.ref_name == 'main' && 'apps/seexr-api-ra/overlays/prod' || 'apps/seexr-api-ra/overlays/dev' }}
#     steps:
#       - uses: actions/checkout@v4

#       # 필요 시 테스트/린트 추가
#       - uses: docker/setup-buildx-action@v3
#       - uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build & Push image
#         uses: docker/build-push-action@v6
#         with:
#           context: ./backend          # ← 실제 소스 폴더
#           file: ./backend/Dockerfile  # ← Dockerfile 경로
#           push: true
#           tags: |
#             ghcr.io/${{ github.repository_owner }}/seexr-api-ra:sha-${{ github.sha }}

#       - name: Checkout infra repo
#         uses: actions/checkout@v4
#         with:
#           repository: ${{ env.INFRA_REPO }}
#           token: ${{ secrets.INFRA_REPO_TOKEN }}   # repo 권한 PAT, 레포 시크릿으로 저장
#           path: infra

#       - name: Install kustomize
#         run: |
#           KVER=v5.4.2
#           curl -sSL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KVER}/kustomize_${KVER}_linux_amd64.tar.gz" -o kustomize.tgz
#           tar xzf kustomize.tgz
#           sudo mv kustomize /usr/local/bin/
#           kustomize version

#       - name: Bump image tag with kustomize
#         working-directory: infra/apps/seexr-api-ra/overlays/prod
#         run: |
#           kustomize edit set image ${{ env.IMAGE }}=${{ env.IMAGE }}":${{ env.TAG_SHA }}"
#           echo "----- after bump"; cat kustomization.yaml

#       - name: Create PR to infra
#         uses: peter-evans/create-pull-request@v6
#         with:
#           token: ${{ secrets.INFRA_REPO_TOKEN }}
#           path: infra
#           base: main
#           branch: ci/api-ra-${{ env.TAG_SHA }}
#           title: "bump(api-ra): ${{ env.TAG_SHA }}"
#           commit-message: "bump(api-ra): ${{ env.TAG_SHA }}"
