name: Build & Bump Infra
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/seexr-api-ra   # 서비스별로 수정
      TAG_SHA: sha-${{ github.sha }}
      INFRA_REPO: pikaybh/seexr-infra                              # 본인 것으로 수정
      OVERLAY_PATH: ${{ github.ref_name == 'main' && 'apps/seexr-api-ra/overlays/prod' || 'apps/seexr-api-ra/overlays/dev' }}
    steps:
      - uses: actions/checkout@v4

      # 필요 시 테스트/린트 추가
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend          # ← 실제 소스 폴더
          file: ./backend/Dockerfile  # ← Dockerfile 경로
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/seexr-api-ra:sha-${{ github.sha }}

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO }}
          token: ${{ secrets.INFRA_REPO_TOKEN }}   # repo 권한 PAT, 레포 시크릿으로 저장
          path: infra

      - name: Bump kustomize image tag
        working-directory: infra/apps/seexr-api-ra/overlays/prod
        run: |
          # .images가 없으면 생성하고, 있으면 대상 name의 newTag만 바꿉니다.
          yq -i '
            .images = (.images // []) |
            if ((.images | map(select(.name == ${{ env.IMAGE }})) | length) > 0) then
              (.images[] | select(.name == ${{ env.IMAGE }})).newTag = ${{ env.TAG_SHA }}
            else
              .images += [{"name": ${{ env.IMAGE }}, "newTag": ${{ env.TAG_SHA }}}]
            end
          ' kustomization.yaml

      - name: Create PR to infra
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra
          base: main
          branch: ci/api-ra-${{ env.TAG_SHA }}
          title: "bump(api-ra): ${{ env.TAG_SHA }}"
          commit-message: "bump(api-ra): ${{ env.TAG_SHA }}"
